//! Tempo benchmark: our detector vs. Rekordbox, and vs. the `stratum-dsp` crate.
//!
//! This is item B7 from `docs/FUTURE_CONSIDERATIONS.md` — the gate that decides
//! whether an off-the-shelf crate replaces the hand-written DSP in
//! `audio/bpm.rs`, or whether we keep ours and have written evidence for it.
//! Nothing about the analysis pipeline should change before this has run.
//!
//! Two kinds of test live here on purpose:
//!
//! - the pure scoring logic (reference parsing, filename hashing, how a
//!   detected tempo is judged) — plain `#[test]`s that CI runs on every push,
//!   because they need no audio at all;
//! - [`benchmark`], which needs a real library on disk and is therefore
//!   `#[ignore]`d. It is a measurement, not a pass/fail assertion.
//!
//! Run the measurement — **`--release` is not optional**. The profile override
//! in `Cargo.toml` optimises dependencies only, so a debug run would time an
//! unoptimised `detect_bpm` against a fully optimised `stratum-dsp` and make our
//! detector look several times slower than it is:
//!
//! ```text
//! REKORD_BENCH_DIR="$HOME/Music/Library" \
//!   cargo test --release --test dsp_bench -- --ignored --nocapture
//! ```
//!
//! Environment:
//! - `REKORD_BENCH_DIR`   library folder to search (required)
//! - `REKORD_BENCH_LIMIT` stop after N matched tracks (default: all)
//! - `REKORD_BENCH_FULL_TRACK` feed `stratum-dsp` the whole track instead of the
//!                        same 120 s excerpt our detector gets. Answers "what
//!                        does the extra input buy?" — at roughly five times the
//!                        memory and 2.5 times the analysis cost, so use it on a
//!                        subset (`REKORD_BENCH_LIMIT`), not on the whole set.
//! - `REKORD_BENCH_TIER`  `steady` = only tracks whose Rekordbox grid holds
//!                        still (drift < 0.5 BPM), `all` (default), `drifting`
//! - `REKORD_BENCH_JOBS`  worker threads (default: cores − 2)
//! - `REKORD_BENCH_MD`    write the summary as markdown to this path
//! - `REKORD_BENCH_CSV`   dump every track's result here, so a follow-up
//!                        question does not need another full run. Contains real
//!                        filenames — keep it out of the repository.
//! - `REKORD_BENCH_MIN_BPM`, `REKORD_BENCH_MAX_BPM` search range for **our**
//!                        detector (B5). Defaults to its own. A range spanning
//!                        exactly one octave makes the octave decision
//!                        deterministic, which is what there is to measure.
//!
//! (An earlier `REKORD_BENCH_WINDOWS` knob measured analysing several excerpts
//! per track — roadmap item B4. It changed the outcome by one track out of 2175
//! at three times the decode cost, so the mechanism was removed again; the
//! numbers are in `docs/DSP_BENCHMARK.md`.)
//!
//! The reference values come from `data/bpm_reference.csv`, generated by
//! `scripts/rekordbox-reference.py` from a Rekordbox XML export. Filenames are
//! stored hashed — see that script for why — so this test hashes what it finds
//! on disk and matches on that.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Mutex;
use std::time::{Duration, Instant};

use sha2::{Digest, Sha256};
use unicode_normalization::UnicodeNormalization;

use rekord_lib_lib::audio::{bpm, decode};
use rekord_lib_lib::audio::bpm::TempoConfig;

/// The reference set travels with the test binary — no path juggling, and it
/// cannot silently go missing.
const REFERENCE_CSV: &str = include_str!("data/bpm_reference.csv");

/// Prefix length of the filename digest. Must match
/// `scripts/rekordbox-reference.py`.
const HASH_LEN: usize = 16;

/// Decode settings of our own detector, mirrored from `audio/bpm.rs`. Mirrored
/// rather than imported because they are private there, and because the point
/// of the benchmark is to measure the pipeline as it actually runs.
const OUR_RATE: u32 = 11025;
const OUR_OFFSET_SECS: u32 = 30;
const OUR_EXCERPT_SECS: u32 = 120;

/// `stratum-dsp` documents itself as tuned for 44.1 kHz over the full track.
const STRATUM_RATE: u32 = 44100;

/// By default `stratum-dsp` gets the **same window** our detector gets, just at
/// its preferred sample rate. Comparing our 120 s excerpt against a full-track
/// analysis would measure engine quality and input length at once and answer
/// neither question; `REKORD_BENCH_FULL_TRACK` runs the other experiment
/// deliberately. It is also what keeps the benchmark inside RAM: 120 s at
/// 44.1 kHz is 21 MB per worker as f32, a ten-minute track is 105 MB, and six
/// workers of the latter put a 16 GB machine into swap — where the run stops
/// measuring DSP and starts measuring the pager.
const STRATUM_EXCERPT_SECS: u32 = 120;

/// Below this the Rekordbox grid is steady enough to treat its `AverageBpm` as
/// a single true tempo.
const STEADY_DRIFT: f32 = 0.5;

/// Tempo range **the reference itself was produced with** — Rekordbox' analysis
/// setting at export time (70–180 BPM, mode "automatic", high-precision grid).
///
/// This matters for scoring: `audio/bpm.rs` searches 60–200 by default, so a
/// track whose real tempo is 185 cannot appear in the reference at 185 —
/// Rekordbox folded it to 92.5. If our detector then says 185, that is counted
/// as an octave error against us even though we may be the one that is right.
/// Octave errors landing outside this window are therefore reported apart.
///
/// Measured since: running our detector at 70–180 too removes this class
/// entirely (42 of them to 0) and does **not** improve accuracy — so these are
/// genuine detector errors that happen to sit outside the window, not artefacts
/// of the mismatch. See `docs/DSP_BENCHMARK.md`.
///
/// **Update these when re-exporting with a different analysis range**, or the
/// report will quietly excuse (or blame) the wrong tracks.
const REFERENCE_MIN_BPM: f32 = 70.0;
const REFERENCE_MAX_BPM: f32 = 180.0;

/// Extensions worth opening, mirroring `AUDIO_EXTENSIONS` in `commands.rs`.
const AUDIO_EXTENSIONS: [&str; 11] = [
    "aiff", "aif", "wav", "flac", "alac", "m4a", "mp3", "aac", "ogg", "opus", "wma",
];

// --- reference set ----------------------------------------------------------

/// One row of the reference set: what Rekordbox says about a track.
#[derive(Debug, Clone, Copy, PartialEq)]
struct Reference {
    /// Rekordbox `AverageBpm`.
    bpm: f32,
    /// Widest minus narrowest tempo of Rekordbox' own grid for this track. A
    /// large value means the reference itself is soft — see [`Tier`].
    drift: f32,
    /// Track length, used to confirm a hash matched the intended file.
    secs: u32,
    /// Rekordbox' key, where the collection was analysed for one.
    key: Option<MusicalKey>,
}

impl Reference {
    fn tier(&self) -> Tier {
        if self.drift < STEADY_DRIFT {
            Tier::Steady
        } else {
            Tier::Drifting
        }
    }
}

/// How solid the reference value is. Scoring a one-number detector against a
/// track whose grid wanders by 20 BPM says nothing about the detector, so the
/// two populations are always reported apart.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum Tier {
    Steady,
    Drifting,
}

/// Parses the reference CSV. Comment lines (`#`) and the header are skipped;
/// malformed rows are skipped rather than fatal, so a hand-edited file degrades
/// instead of failing the run.
fn parse_reference(csv: &str) -> HashMap<String, Reference> {
    let mut out = HashMap::new();
    for line in csv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with("name_sha256") {
            continue;
        }
        let mut cols = line.split(',');
        let (Some(hash), Some(bpm), Some(drift), Some(secs)) =
            (cols.next(), cols.next(), cols.next(), cols.next())
        else {
            continue;
        };
        // The key column arrived later than the rest, so a file without it is
        // still a valid tempo reference rather than a parse failure.
        let key = cols.next().and_then(parse_key);
        let (Ok(bpm), Ok(drift), Ok(secs)) =
            (bpm.parse::<f32>(), drift.parse::<f32>(), secs.parse::<u32>())
        else {
            continue;
        };
        if bpm > 0.0 {
            out.insert(
                hash.to_string(),
                Reference { bpm, drift, secs, key },
            );
        }
    }
    out
}

/// Stable key for a filename. NFC first: the Rekordbox export writes NFC while
/// some files sit on disk in NFD, and hashing raw bytes would then miss exactly
/// those tracks. Must stay in step with `scripts/rekordbox-reference.py`.
fn name_hash(filename: &str) -> String {
    let normalised: String = filename.nfc().collect();
    let digest = Sha256::digest(normalised.as_bytes());
    let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
    hex[..HASH_LEN].to_string()
}

// --- musical keys -----------------------------------------------------------

/// A key as a pitch class (C = 0) plus a mode — the only representation both
/// sides can be compared in. Rekordbox exports a mix of sharps and flats
/// ("F#m", "Abm", "Db"), `stratum-dsp` emits sharps only, and Camelot is a third
/// spelling of the same thing; comparing strings would score `Abm` against
/// `G#m` as a miss.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct MusicalKey {
    /// 0 = C, 1 = C#/Db, … 11 = B.
    pc: u8,
    minor: bool,
}

impl MusicalKey {
    /// Camelot wheel position, in the convention Rekordbox and Mixed In Key
    /// use: **A = minor, B = major**, 8A = A minor, 8B = C major, and one step
    /// up the number is one fifth up.
    ///
    /// Worth stating explicitly because `stratum_dsp::Key::numerical()` uses a
    /// *different* convention (A = major, 1A = C) — writing its output into a
    /// tag as "Camelot" would put every track on the wrong spoke of the wheel.
    /// Human-readable spelling, sharps only — for report tables. Deliberately
    /// not used for comparisons: `Abm` and `G#m` are the same key.
    fn spelled(&self) -> String {
        const NOTES: [&str; 12] = [
            "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B",
        ];
        let (n, is_major) = self.camelot();
        format!(
            "{}{} ({}{})",
            NOTES[self.pc as usize % 12],
            if self.minor { "m" } else { "" },
            n,
            if is_major { "B" } else { "A" }
        )
    }

    fn camelot(&self) -> (u8, bool) {
        let base: i32 = if self.minor { 9 } else { 0 };
        let n = (8 + (self.pc as i32 - base) * 7).rem_euclid(12);
        (if n == 0 { 12 } else { n as u8 }, !self.minor)
    }
}

/// Parses a key from any of the spellings involved: Rekordbox' `Tonality`
/// ("Am", "F#m", "Abm", "C"), spelled-out modes ("A minor", "C major") and
/// Camelot ("8A", "12B"). Returns `None` for an empty or unrecognised value,
/// which is how "never analysed" travels through the benchmark.
fn parse_key(raw: &str) -> Option<MusicalKey> {
    let text = raw.trim();
    if text.is_empty() {
        return None;
    }

    // Camelot first: it is the only form that starts with a digit.
    if text.chars().next()?.is_ascii_digit() {
        let (number, letter) = text.split_at(text.len() - 1);
        let number: i32 = number.trim().parse().ok()?;
        if !(1..=12).contains(&number) {
            return None;
        }
        let minor = match letter.trim().to_ascii_uppercase().as_str() {
            "A" => true,
            "B" => false,
            _ => return None,
        };
        let base: i32 = if minor { 9 } else { 0 };
        let pc = (base + 7 * (number - 8)).rem_euclid(12) as u8;
        return Some(MusicalKey { pc, minor });
    }

    let mut chars = text.chars();
    let note = chars.next()?.to_ascii_uppercase();
    let mut pc: i32 = match note {
        'C' => 0,
        'D' => 2,
        'E' => 4,
        'F' => 5,
        'G' => 7,
        'A' => 9,
        'B' => 11,
        _ => return None,
    };
    let mut rest = chars.as_str();
    // Accidentals, including the typographic ones taggers like to emit.
    if let Some(first) = rest.chars().next() {
        match first {
            '#' | '\u{266f}' => {
                pc += 1;
                rest = &rest[first.len_utf8()..];
            }
            'b' | '\u{266d}' => {
                pc -= 1;
                rest = &rest[first.len_utf8()..];
            }
            _ => {}
        }
    }
    let mode = rest.trim().to_ascii_lowercase();
    let minor = match mode.as_str() {
        "" | "maj" | "major" => false,
        "m" | "min" | "minor" => true,
        _ => return None,
    };
    Some(MusicalKey {
        pc: pc.rem_euclid(12) as u8,
        minor,
    })
}

/// `stratum-dsp`'s key in our representation. Taken from the enum rather than
/// from `name()`, so no string round-trip can mangle it.
fn from_stratum(key: stratum_dsp::Key) -> MusicalKey {
    match key {
        stratum_dsp::Key::Major(pc) => MusicalKey {
            pc: (pc % 12) as u8,
            minor: false,
        },
        stratum_dsp::Key::Minor(pc) => MusicalKey {
            pc: (pc % 12) as u8,
            minor: true,
        },
    }
}

/// How a detected key relates to the reference. The two "near" classes are not
/// charity: a relative or fifth-neighbour key is what DJs treat as mixable, and
/// key detectors fail in exactly those two directions, so lumping them in with
/// "wrong" would hide whether the detector is roughly right or lost.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum KeyVerdict {
    Exact,
    /// Parallel key — right tonic, wrong mode (Am vs A). Counted apart because
    /// it is a *mode* decision that failed, not a pitch one: the chroma analysis
    /// found the right root and then picked the wrong third. It sits far away on
    /// the Camelot wheel, so it is no help for mixing — but it says something
    /// completely different about the detector than a random miss does.
    Parallel,
    /// Relative major/minor — same Camelot number, other letter (Am vs C).
    Relative,
    /// One step around the wheel, same mode (Am vs Em).
    Fifth,
    Wrong,
    NoResult,
}

fn classify_key(detected: Option<MusicalKey>, reference: MusicalKey) -> KeyVerdict {
    let Some(got) = detected else {
        return KeyVerdict::NoResult;
    };
    if got == reference {
        return KeyVerdict::Exact;
    }
    if got.pc == reference.pc {
        return KeyVerdict::Parallel;
    }
    let (gn, gmaj) = got.camelot();
    let (rn, rmaj) = reference.camelot();
    if gn == rn && gmaj != rmaj {
        return KeyVerdict::Relative;
    }
    let step = (gn as i32 - rn as i32).rem_euclid(12);
    if gmaj == rmaj && (step == 1 || step == 11) {
        return KeyVerdict::Fifth;
    }
    KeyVerdict::Wrong
}

/// Tally of key verdicts.
#[derive(Debug, Default, Clone, Copy)]
struct KeyTally {
    exact: usize,
    parallel: usize,
    relative: usize,
    fifth: usize,
    wrong: usize,
    none: usize,
}

impl KeyTally {
    fn add(&mut self, verdict: KeyVerdict) {
        match verdict {
            KeyVerdict::Exact => self.exact += 1,
            KeyVerdict::Parallel => self.parallel += 1,
            KeyVerdict::Relative => self.relative += 1,
            KeyVerdict::Fifth => self.fifth += 1,
            KeyVerdict::Wrong => self.wrong += 1,
            KeyVerdict::NoResult => self.none += 1,
        }
    }

    fn total(&self) -> usize {
        self.exact + self.parallel + self.relative + self.fifth + self.wrong + self.none
    }

    fn pct(&self, n: usize) -> f32 {
        if self.total() == 0 {
            0.0
        } else {
            n as f32 * 100.0 / self.total() as f32
        }
    }
}

// --- scoring ----------------------------------------------------------------

/// How a detected tempo relates to the reference.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Verdict {
    /// Within half a BPM — indistinguishable in practice.
    Exact,
    /// Within two BPM. Still usable for sorting and mixing.
    Close,
    /// A musically related multiple: the classic autocorrelation failure, and
    /// worth counting apart from noise because it is fixable by better octave
    /// folding rather than by a better estimator.
    Octave,
    /// Wrong, and not by a recognisable ratio.
    Wrong,
    /// The detector declined to answer. Not a win, but not a wrong tag either.
    NoResult,
}

/// Ratios a wrong-but-related answer tends to land on: halves and doubles, plus
/// the triplet/shuffle ratios that `audio/bpm.rs` already folds over.
const OCTAVE_RATIOS: [f32; 10] = [
    0.25,
    1.0 / 3.0,
    0.5,
    2.0 / 3.0,
    0.75,
    4.0 / 3.0,
    1.5,
    2.0,
    3.0,
    4.0,
];

/// Judges one detection. `None` means the detector returned nothing.
fn classify(detected: Option<f32>, reference: f32) -> Verdict {
    let Some(got) = detected else {
        return Verdict::NoResult;
    };
    if reference <= 0.0 {
        return Verdict::Wrong;
    }
    let diff = (got - reference).abs();
    if diff <= 0.5 {
        return Verdict::Exact;
    }
    if diff <= 2.0 {
        return Verdict::Close;
    }
    // Judged on the ratio, so the tolerance scales with the tempo instead of
    // being generous at 70 BPM and strict at 170.
    let ratio = got / reference;
    if OCTAVE_RATIOS.iter().any(|r| (ratio / r - 1.0).abs() <= 0.02) {
        return Verdict::Octave;
    }
    Verdict::Wrong
}

/// What one engine produced for one track, and what it cost. Decode and
/// analysis are timed apart on purpose: decoding is a knob we control (sample
/// rate, excerpt length), the analysis is the engine's own price. Rolling them
/// into one number would hide which of the two a slow engine is actually
/// spending its time on.
#[derive(Debug, Clone, Copy)]
struct Timed {
    verdict: Verdict,
    decode: Duration,
    analyze: Duration,
    /// An octave error whose answer lies outside the reference's own tempo
    /// range — the reference could not have agreed with it even if it were
    /// right. See [`REFERENCE_MIN_BPM`].
    unreachable_octave: bool,
}

/// Could the reference even represent this answer? Only meaningful for octave
/// errors, where the two candidates are a factor apart and one of them may sit
/// outside the range Rekordbox was allowed to report.
fn outside_reference_range(detected: Option<f32>) -> bool {
    detected.is_some_and(|bpm| bpm < REFERENCE_MIN_BPM || bpm > REFERENCE_MAX_BPM)
}

/// Tally of verdicts for one engine over one tier.
#[derive(Debug, Default, Clone, Copy)]
struct Tally {
    exact: usize,
    close: usize,
    octave: usize,
    wrong: usize,
    none: usize,
    /// Subset of `octave`: errors the reference's range could not have matched.
    unreachable_octave: usize,
    decode_time: Duration,
    analyze_time: Duration,
}

impl Tally {
    fn add(&mut self, timed: Timed) {
        match timed.verdict {
            Verdict::Exact => self.exact += 1,
            Verdict::Close => self.close += 1,
            Verdict::Octave => self.octave += 1,
            Verdict::Wrong => self.wrong += 1,
            Verdict::NoResult => self.none += 1,
        }
        if timed.unreachable_octave && timed.verdict == Verdict::Octave {
            self.unreachable_octave += 1;
        }
        self.decode_time += timed.decode;
        self.analyze_time += timed.analyze;
    }

    fn total(&self) -> usize {
        self.exact + self.close + self.octave + self.wrong + self.none
    }

    /// Share within ±0.5 BPM.
    fn exact_pct(&self) -> f32 {
        self.pct(self.exact)
    }

    /// Share within ±2 BPM, which is what "correct" means for DJ use.
    fn usable_pct(&self) -> f32 {
        self.pct(self.exact + self.close)
    }

    fn pct(&self, n: usize) -> f32 {
        if self.total() == 0 {
            0.0
        } else {
            n as f32 * 100.0 / self.total() as f32
        }
    }

    fn decode_ms(&self) -> f32 {
        self.per_track(self.decode_time)
    }

    fn analyze_ms(&self) -> f32 {
        self.per_track(self.analyze_time)
    }

    fn per_track(&self, total: Duration) -> f32 {
        if self.total() == 0 {
            0.0
        } else {
            total.as_secs_f32() * 1000.0 / self.total() as f32
        }
    }
}

// --- decoding ---------------------------------------------------------------

/// The bundled sidecar, so the benchmark decodes exactly like the app does.
fn ffmpeg() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("binaries")
        .join("ffmpeg-aarch64-apple-darwin")
}

/// Decodes mono `s16le` through the sidecar. `secs == 0` reads to the end.
///
/// Unlike `audio::decode::mono_pcm` this shells out directly instead of going
/// through the Tauri shell plugin — there is no app here, and the plugin is
/// only needed for its event stream.
fn decode_pcm(path: &Path, rate: u32, offset_secs: u32, secs: u32) -> Option<Vec<i16>> {
    let mut cmd = Command::new(ffmpeg());
    cmd.args(["-v", "error"]);
    if offset_secs > 0 {
        cmd.args(["-ss", &offset_secs.to_string()]);
    }
    cmd.arg("-i").arg(path).args(["-map", "0:a:0"]);
    if secs > 0 {
        cmd.args(["-t", &secs.to_string()]);
    }
    cmd.args(["-ac", "1", "-ar", &rate.to_string(), "-f", "s16le", "pipe:1"]);

    let out = cmd.output().ok()?;
    if !out.status.success() {
        return None;
    }
    Some(decode::to_samples(&out.stdout))
}

/// One excerpt as our detector sees it, falling back to the start for a file
/// shorter than the offset — the same rule as `bpm::analyze_bpm`.
fn our_excerpt(path: &Path, offset: u32) -> Option<Vec<i16>> {
    let full = |offset| decode_pcm(path, OUR_RATE, offset, OUR_EXCERPT_SECS);
    match full(offset) {
        Some(s) if s.len() >= OUR_RATE as usize * 10 => Some(s),
        _ if offset > 0 => full(0),
        other => other,
    }
}

// --- the run ----------------------------------------------------------------

/// One track's result, kept for the per-track table.
struct Row {
    name: String,
    reference: Reference,
    ours: Option<f32>,
    stratum: Option<f32>,
    /// `stratum-dsp`'s key. Ours has none — that absence is what B1 is about.
    stratum_key: Option<MusicalKey>,
    /// How much our detector trusted its own answer. Dumped per track so the
    /// write threshold in `commands.rs` can be picked from measured data rather
    /// than guessed: a confidence that does not track correctness would be worse
    /// than none, because it gates writes into users' files.
    our_confidence: Option<f32>,
}

fn collect_audio_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_audio_files(&path, out);
        } else if path
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| AUDIO_EXTENSIONS.contains(&e.to_lowercase().as_str()))
            .unwrap_or(false)
        {
            out.push(path);
        }
    }
}

fn env_usize(key: &str) -> Option<usize> {
    std::env::var(key).ok()?.trim().parse().ok()
}

fn env_f32(key: &str) -> Option<f32> {
    std::env::var(key).ok()?.trim().parse().ok()
}

/// Our detector's configuration for this run, so the range and the window count
/// can be swept without touching the code they are being measured against.
fn tempo_config_from_env() -> TempoConfig {
    let default = TempoConfig::default();
    TempoConfig {
        min_bpm: env_f32("REKORD_BENCH_MIN_BPM").unwrap_or(default.min_bpm),
        max_bpm: env_f32("REKORD_BENCH_MAX_BPM").unwrap_or(default.max_bpm),
    }
}

#[test]
#[ignore = "needs a real library on disk; set REKORD_BENCH_DIR"]
fn benchmark() {
    let Ok(dir) = std::env::var("REKORD_BENCH_DIR") else {
        panic!("set REKORD_BENCH_DIR to the library folder to benchmark against");
    };
    let reference = parse_reference(REFERENCE_CSV);
    assert!(!reference.is_empty(), "reference set is empty");

    let tier_filter = std::env::var("REKORD_BENCH_TIER").unwrap_or_else(|_| "all".into());
    let limit = env_usize("REKORD_BENCH_LIMIT").unwrap_or(usize::MAX);
    let full_track = std::env::var("REKORD_BENCH_FULL_TRACK").is_ok();
    let our_config = tempo_config_from_env();
    let jobs = env_usize("REKORD_BENCH_JOBS").unwrap_or_else(|| {
        std::thread::available_parallelism()
            .map(|n| n.get().saturating_sub(2).max(1))
            .unwrap_or(4)
    });

    // Match the library against the reference set before decoding anything, so
    // a mistyped folder fails in a second rather than in an hour.
    let mut files = Vec::new();
    collect_audio_files(Path::new(&dir), &mut files);
    let mut work: Vec<(PathBuf, String, Reference)> = Vec::new();
    for path in &files {
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let hash = name_hash(name);
        let Some(reference) = reference.get(&hash) else {
            continue;
        };
        let keep = match tier_filter.as_str() {
            "steady" => reference.tier() == Tier::Steady,
            "drifting" => reference.tier() == Tier::Drifting,
            _ => true,
        };
        if keep {
            work.push((path.clone(), hash, *reference));
        }
    }
    work.sort_by(|a, b| a.1.cmp(&b.1));
    work.truncate(limit);

    println!(
        "\nours: {:.0}-{:.0} BPM",
        our_config.min_bpm, our_config.max_bpm
    );
    println!(
        "{} audio files under {dir}\n{} reference rows, {} matched, tier '{}', \
         stratum input: {}, {jobs} threads\n",
        files.len(),
        reference.len(),
        work.len(),
        tier_filter,
        if full_track {
            "whole track".to_string()
        } else {
            format!("{STRATUM_EXCERPT_SECS} s excerpt, same as ours")
        },
    );
    assert!(
        !work.is_empty(),
        "no file under {dir} matched the reference set — wrong folder, or the \
         collection has been renamed since the export"
    );

    let next = AtomicUsize::new(0);
    let done = AtomicUsize::new(0);
    let rows: Mutex<Vec<Row>> = Mutex::new(Vec::with_capacity(work.len()));
    let mut ours_tally: HashMap<Tier, Tally> = HashMap::new();
    let mut stratum_tally: HashMap<Tier, Tally> = HashMap::new();
    let timings: Mutex<Vec<(Tier, Option<KeyVerdict>, Timed, Timed)>> = Mutex::new(Vec::new());
    let started = Instant::now();

    std::thread::scope(|scope| {
        for _ in 0..jobs {
            scope.spawn(|| loop {
                let index = next.fetch_add(1, Ordering::Relaxed);
                let Some((path, _hash, reference)) = work.get(index) else {
                    return;
                };

                // Ours: the excerpt the scan uses, at 11 kHz.
                let t0 = Instant::now();
                let excerpt = our_excerpt(path, OUR_OFFSET_SECS);
                let our_decode = t0.elapsed();
                let t0 = Instant::now();
                let detected =
                    excerpt.and_then(|s| bpm::detect_bpm_with(&s, OUR_RATE, our_config));
                let our_analyze = t0.elapsed();
                let ours = detected.map(|t| t.bpm);
                let our_confidence = detected.map(|t| t.confidence);

                // stratum-dsp: 44.1 kHz, mono f32 in [-1, 1], same window as
                // ours unless the full-track experiment was asked for.
                let t1 = Instant::now();
                let (offset, secs) = if full_track {
                    (0, 0)
                } else {
                    (OUR_OFFSET_SECS, STRATUM_EXCERPT_SECS)
                };
                let samples = decode_pcm(path, STRATUM_RATE, offset, secs).map(|pcm| {
                    // Converted and then dropped straight away: a ten-minute
                    // track is ~50 MB as i16 and ~105 MB as f32, and holding
                    // both per worker is what turns this into gigabytes.
                    let out: Vec<f32> = pcm.iter().map(|s| *s as f32 / 32768.0).collect();
                    drop(pcm);
                    out
                });
                let stratum_decode = t1.elapsed();
                let t1 = Instant::now();
                let analysed = samples.and_then(|samples| {
                    stratum_dsp::analyze_audio(
                        &samples,
                        STRATUM_RATE,
                        stratum_dsp::AnalysisConfig::default(),
                    )
                    .ok()
                });
                let stratum_analyze = t1.elapsed();
                let stratum = analysed.as_ref().map(|r| r.bpm);
                let stratum_key = analysed.as_ref().map(|r| from_stratum(r.key));

                timings.lock().unwrap().push((
                    reference.tier(),
                    reference.key.map(|r| classify_key(stratum_key, r)),
                    Timed {
                        verdict: classify(ours, reference.bpm),
                        decode: our_decode,
                        analyze: our_analyze,
                        unreachable_octave: outside_reference_range(ours),
                    },
                    Timed {
                        verdict: classify(stratum, reference.bpm),
                        decode: stratum_decode,
                        analyze: stratum_analyze,
                        unreachable_octave: outside_reference_range(stratum),
                    },
                ));
                rows.lock().unwrap().push(Row {
                    name: path
                        .file_name()
                        .and_then(|n| n.to_str())
                        .unwrap_or("?")
                        .to_string(),
                    reference: *reference,
                    ours,
                    stratum,
                    stratum_key,
                    our_confidence,
                });

                let n = done.fetch_add(1, Ordering::Relaxed) + 1;
                if n % 25 == 0 || n == work.len() {
                    println!("  {n}/{} analysed", work.len());
                }
            });
        }
    });

    let mut key_tally = KeyTally::default();
    for (tier, key_verdict, our_timed, stratum_timed) in timings.into_inner().unwrap() {
        ours_tally.entry(tier).or_default().add(our_timed);
        stratum_tally.entry(tier).or_default().add(stratum_timed);
        // Only tracks Rekordbox has a key for can score one.
        if let Some(v) = key_verdict {
            key_tally.add(v);
        }
    }

    let mut rows = rows.into_inner().unwrap();
    rows.sort_by(|a, b| a.reference.bpm.total_cmp(&b.reference.bpm));
    let report = report(
        &rows,
        &ours_tally,
        &stratum_tally,
        &key_tally,
        started.elapsed(),
        full_track,
        our_config,
    );
    println!("{report}");

    if let Ok(path) = std::env::var("REKORD_BENCH_MD") {
        std::fs::write(&path, &report).expect("could not write the markdown summary");
        println!("summary written to {path}");
    }
    if let Ok(path) = std::env::var("REKORD_BENCH_CSV") {
        std::fs::write(&path, per_track_csv(&rows)).expect("could not write the csv dump");
        println!("per-track results written to {path}");
    }
}

/// Every track's raw result. Written only on request and never committed: it
/// carries the real filenames, which is exactly what the hashed reference set
/// exists to keep out of the repository.
fn per_track_csv(rows: &[Row]) -> String {
    let mut out = String::from(
        "file,ref_bpm,drift,ref_key,ours,our_confidence,our_verdict,stratum,stratum_verdict,stratum_key,key_verdict\n",
    );
    for r in rows {
        let num = |v: Option<f32>| v.map(|x| format!("{x:.2}")).unwrap_or_default();
        let key = |v: Option<MusicalKey>| v.map(|k| k.spelled()).unwrap_or_default();
        out.push_str(&format!(
            "\"{}\",{:.2},{:.2},{},{},{},{:?},{},{:?},{},{}\n",
            r.name.replace('"', "'"),
            r.reference.bpm,
            r.reference.drift,
            key(r.reference.key),
            num(r.ours),
            r.our_confidence
                .map(|c| format!("{c:.3}"))
                .unwrap_or_default(),
            classify(r.ours, r.reference.bpm),
            num(r.stratum),
            classify(r.stratum, r.reference.bpm),
            key(r.stratum_key),
            r.reference
                .key
                .map(|want| format!("{:?}", classify_key(r.stratum_key, want)))
                .unwrap_or_default(),
        ));
    }
    out
}

/// The whole comparison as markdown, so the same text can go to the terminal
/// and into `docs/DSP_BENCHMARK.md` without being retyped.
fn report(
    rows: &[Row],
    ours: &HashMap<Tier, Tally>,
    stratum: &HashMap<Tier, Tally>,
    keys: &KeyTally,
    wall: Duration,
    full_track: bool,
    our_config: TempoConfig,
) -> String {
    let mut out = String::new();
    out.push_str("\n## Results\n\n");
    out.push_str(&format!(
        "Our detector: {:.0}–{:.0} BPM.\n\n",
        our_config.min_bpm, our_config.max_bpm
    ));
    out.push_str(&format!(
        "Reference: Rekordbox, analysed at {REFERENCE_MIN_BPM:.0}–{REFERENCE_MAX_BPM:.0} BPM \
         (mode \"automatic\", high-precision grid). Our detector searches 60–200, so \
         answers outside the reference range cannot be confirmed by it.\n\n"
    ));
    out.push_str(&format!(
        "{} tracks, {:.1} min wall clock. Our detector saw a {OUR_EXCERPT_SECS} s \
         excerpt at {} kHz from {OUR_OFFSET_SECS} s in; stratum-dsp saw {} at \
         {:.1} kHz.\n\n",
        rows.len(),
        wall.as_secs_f32() / 60.0,
        OUR_RATE as f32 / 1000.0,
        if full_track {
            "the whole track".to_string()
        } else {
            format!("the same {STRATUM_EXCERPT_SECS} s window")
        },
        STRATUM_RATE as f32 / 1000.0,
    ));

    for (tier, label, note) in [
        (
            Tier::Steady,
            "Steady grid (drift < 0.5 BPM)",
            "The reference is a single, solid number here — this is the table that decides.",
        ),
        (
            Tier::Drifting,
            "Drifting grid (drift >= 0.5 BPM)",
            "Rekordbox' own grid wanders within these tracks, so a miss may be the reference's fault.",
        ),
    ] {
        let (Some(o), Some(s)) = (ours.get(&tier), stratum.get(&tier)) else {
            continue;
        };
        out.push_str(&format!("### {label} — {} tracks\n\n{note}\n\n", o.total()));
        out.push_str(
            "| engine | ±0.5 BPM | ±2 BPM | octave error | wrong | no result | decode ms | analyse ms |\n",
        );
        out.push_str("|---|---|---|---|---|---|---|---|\n");
        for (name, t) in [("ours", o), ("stratum-dsp", s)] {
            out.push_str(&format!(
                "| {name} | {} ({:.1} %) | {} ({:.1} %) | {} | {} | {} | {:.0} | {:.0} |\n",
                t.exact,
                t.exact_pct(),
                t.exact + t.close,
                t.usable_pct(),
                t.octave,
                t.wrong,
                t.none,
                t.decode_ms(),
                t.analyze_ms(),
            ));
        }
        let unreachable: usize = o.unreachable_octave + s.unreachable_octave;
        if unreachable > 0 {
            out.push_str(&format!(
                "Of the octave errors above, {} (ours: {}, stratum-dsp: {}) answer outside \
                 {REFERENCE_MIN_BPM:.0}–{REFERENCE_MAX_BPM:.0} BPM. The reference could not \
                 have reported those values at all, so the reference can neither \
                 confirm nor refute them. Running our detector at the same range \
                 was measured and removes this class without improving accuracy, \
                 so treat it as unjudgeable rather than as excused.\n\n",
                unreachable, o.unreachable_octave, s.unreachable_octave,
            ));
        }
        out.push('\n');
    }

    // Key detection: only stratum-dsp has an entry here, which is the whole
    // point of B1 — we produce no key at all, so the question is not "is it
    // better than ours" but "is it good enough to adopt".
    if keys.total() > 0 {
        out.push_str(&format!(
            "### Key detection — {} tracks\n\nOnly stratum-dsp appears here: we \
             detect no key today. Camelot is derived from the pitch class, not from \
             `Key::numerical()`, whose A/B convention is the inverse of \
             Rekordbox'.\n\n",
            keys.total()
        ));
        out.push_str(
            "| engine | exact | parallel (Am/A) | relative (Am/C) | fifth neighbour | wrong | no result |\n",
        );
        out.push_str("|---|---|---|---|---|---|---|\n");
        out.push_str(&format!(
            "| stratum-dsp | {} ({:.1} %) | {} ({:.1} %) | {} ({:.1} %) | {} ({:.1} %) | {} ({:.1} %) | {} |\n\n",
            keys.exact,
            keys.pct(keys.exact),
            keys.parallel,
            keys.pct(keys.parallel),
            keys.relative,
            keys.pct(keys.relative),
            keys.fifth,
            keys.pct(keys.fifth),
            keys.wrong,
            keys.pct(keys.wrong),
            keys.none,
        ));

        // A sample of the misses, because *how* a key detector is wrong matters:
        // a consistent semitone offset is a tuning problem, scattered errors are
        // a weak detector, and a pile of relatives is barely a problem at all.
        let mut misses: Vec<(&Row, MusicalKey, MusicalKey)> = rows
            .iter()
            .filter_map(|r| {
                let want = r.reference.key?;
                let got = r.stratum_key?;
                (classify_key(Some(got), want) == KeyVerdict::Wrong).then_some((r, want, got))
            })
            .collect();
        misses.sort_by(|a, b| a.0.name.cmp(&b.0.name));
        if !misses.is_empty() {
            out.push_str(&format!(
                "Outright key misses, first {} of {}:\n\n| Rekordbox | stratum-dsp | semitones off | file |\n|---|---|---|---|\n",
                misses.len().min(20),
                misses.len()
            ));
            for (row, want, got) in misses.iter().take(20) {
                let semitones = (got.pc as i32 - want.pc as i32).rem_euclid(12);
                out.push_str(&format!(
                    "| {} | {} | {} | `{}` |\n",
                    want.spelled(),
                    got.spelled(),
                    semitones,
                    row.name,
                ));
            }
            out.push('\n');
        }
    }

    // The tracks where the two engines disagree are where the interesting
    // material is — a shared miss is usually the reference, not the detector.
    let mut disagreements: Vec<&Row> = rows
        .iter()
        .filter(|r| {
            let a = classify(r.ours, r.reference.bpm);
            let b = classify(r.stratum, r.reference.bpm);
            let good = |v: Verdict| matches!(v, Verdict::Exact | Verdict::Close);
            good(a) != good(b)
        })
        .collect();
    disagreements.sort_by(|a, b| a.reference.bpm.total_cmp(&b.reference.bpm));
    out.push_str(&format!(
        "### Disagreements — {} tracks\n\nOne engine gets these right and the other does not.\n\n",
        disagreements.len()
    ));
    out.push_str("| reference | drift | ours | stratum-dsp | file |\n|---|---|---|---|---|\n");
    for r in disagreements.iter().take(40) {
        let fmt = |v: Option<f32>| match v {
            Some(x) => format!("{x:.2}"),
            None => "—".into(),
        };
        out.push_str(&format!(
            "| {:.2} | {:.2} | {} | {} | `{}` |\n",
            r.reference.bpm,
            r.reference.drift,
            fmt(r.ours),
            fmt(r.stratum),
            r.name,
        ));
    }
    if disagreements.len() > 40 {
        out.push_str(&format!(
            "\n_{} further disagreements not listed._\n",
            disagreements.len() - 40
        ));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_the_committed_reference_set() {
        let refs = parse_reference(REFERENCE_CSV);
        assert!(
            refs.len() > 500,
            "expected a substantial reference set, got {}",
            refs.len()
        );
        for (hash, r) in &refs {
            assert_eq!(hash.len(), HASH_LEN, "hash {hash} has the wrong length");
            assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
            assert!(r.bpm > 30.0 && r.bpm < 300.0, "implausible bpm {}", r.bpm);
            assert!(r.drift >= 0.0);
        }
    }

    #[test]
    fn reference_parsing_skips_comments_header_and_junk() {
        let csv = "# a comment\nname_sha256,bpm,drift,secs\n\
                   aabbccdd00112233,128.00,0.10,300\n\
                   deadbeefdeadbeef,not-a-number,0,0\n\
                   short,120,0,0\n\
                   00112233aabbccdd,0.00,0,0\n";
        let refs = parse_reference(csv);
        // The malformed row is skipped, the zero-BPM row too; "short" survives
        // parsing because the hash length is the generator's business, not the
        // parser's — but it can never match a real digest.
        assert_eq!(refs.len(), 2);
        assert_eq!(refs["aabbccdd00112233"].bpm, 128.0);
        assert_eq!(refs["aabbccdd00112233"].drift, 0.10);
        assert_eq!(refs["aabbccdd00112233"].secs, 300);
        assert!(!refs.contains_key("deadbeefdeadbeef"));
    }

    #[test]
    fn empty_reference_is_empty_not_a_panic() {
        assert!(parse_reference("").is_empty());
        assert!(parse_reference("# only comments\n").is_empty());
    }

    #[test]
    fn name_hash_matches_the_python_generator() {
        // Cross-checked against
        //   python3 -c "import hashlib,unicodedata; print(hashlib.sha256(
        //     unicodedata.normalize('NFC','...').encode()).hexdigest()[:16])"
        assert_eq!(name_hash("track.aiff"), "a717144d7bdcbd6d");
        assert_eq!(name_hash(""), "e3b0c44298fc1c14");
    }

    #[test]
    fn name_hash_is_normalisation_insensitive() {
        // The export writes NFC, the filesystem may hold NFD. Both must land on
        // the same row, or those tracks silently drop out of the benchmark.
        let nfc = "Oaxaque\u{f1}o.aiff"; // ñ as one code point
        let nfd = "Oaxaquen\u{303}o.aiff"; // n + combining tilde
        assert_ne!(nfc, nfd, "the test inputs must differ as bytes");
        assert_eq!(name_hash(nfc), name_hash(nfd));
    }

    #[test]
    fn classify_grades_by_distance() {
        assert_eq!(classify(Some(128.0), 128.0), Verdict::Exact);
        assert_eq!(classify(Some(128.4), 128.0), Verdict::Exact);
        assert_eq!(classify(Some(129.5), 128.0), Verdict::Close);
        assert_eq!(classify(Some(132.0), 128.0), Verdict::Wrong);
        assert_eq!(classify(None, 128.0), Verdict::NoResult);
    }

    #[test]
    fn classify_separates_octave_errors_from_noise() {
        // Half, double and the triplet ratios are a different failure than
        // "no idea", because octave folding is what fixes them.
        assert_eq!(classify(Some(64.0), 128.0), Verdict::Octave);
        assert_eq!(classify(Some(256.0), 128.0), Verdict::Octave);
        assert_eq!(classify(Some(85.33), 128.0), Verdict::Octave); // 2/3
        assert_eq!(classify(Some(170.67), 128.0), Verdict::Octave); // 4/3
        assert_eq!(classify(Some(96.0), 128.0), Verdict::Octave); // 3/4
        // Not a recognised ratio.
        assert_eq!(classify(Some(110.0), 128.0), Verdict::Wrong);
    }

    #[test]
    fn classify_handles_a_useless_reference() {
        assert_eq!(classify(Some(128.0), 0.0), Verdict::Wrong);
    }

    fn timed(verdict: Verdict) -> Timed {
        Timed {
            verdict,
            decode: Duration::from_millis(30),
            analyze: Duration::from_millis(10),
            unreachable_octave: false,
        }
    }

    #[test]
    fn tally_percentages_count_close_as_usable() {
        let mut t = Tally::default();
        t.add(timed(Verdict::Exact));
        t.add(timed(Verdict::Close));
        t.add(timed(Verdict::Octave));
        t.add(timed(Verdict::NoResult));
        assert_eq!(t.total(), 4);
        assert_eq!(t.exact_pct(), 25.0);
        assert_eq!(t.usable_pct(), 50.0);
    }

    #[test]
    fn tally_keeps_decode_and_analysis_cost_apart() {
        // The whole point of the split: an engine can be cheap to run and
        // expensive to feed, and the report has to be able to say which.
        let mut t = Tally::default();
        t.add(timed(Verdict::Exact));
        t.add(timed(Verdict::Exact));
        assert_eq!(t.decode_ms(), 30.0);
        assert_eq!(t.analyze_ms(), 10.0);
    }

    #[test]
    fn octave_errors_outside_the_reference_range_are_counted_apart() {
        // 190 BPM cannot appear in a 70-180 reference, so an octave error there
        // may be the range, not the detector. 95 BPM can, so it counts fully.
        assert!(outside_reference_range(Some(190.0)));
        assert!(outside_reference_range(Some(65.0)));
        assert!(!outside_reference_range(Some(95.0)));
        assert!(!outside_reference_range(None));

        let mut t = Tally::default();
        t.add(Timed { unreachable_octave: true, ..timed(Verdict::Octave) });
        t.add(Timed { unreachable_octave: false, ..timed(Verdict::Octave) });
        // Flagged but not an octave error: must not be counted.
        t.add(Timed { unreachable_octave: true, ..timed(Verdict::Exact) });
        assert_eq!(t.octave, 2);
        assert_eq!(t.unreachable_octave, 1);
    }

    #[test]
    fn empty_tally_does_not_divide_by_zero() {
        let t = Tally::default();
        assert_eq!(t.exact_pct(), 0.0);
        assert_eq!(t.usable_pct(), 0.0);
        assert_eq!(t.decode_ms(), 0.0);
        assert_eq!(t.analyze_ms(), 0.0);
    }

    #[test]
    fn tier_splits_at_the_steady_threshold() {
        let steady = Reference { bpm: 128.0, drift: 0.49, secs: 300, key: None };
        let drifting = Reference { bpm: 128.0, drift: 0.5, secs: 300, key: None };
        assert_eq!(steady.tier(), Tier::Steady);
        assert_eq!(drifting.tier(), Tier::Drifting);
    }

    #[test]
    fn the_reference_set_has_both_tiers() {
        let refs = parse_reference(REFERENCE_CSV);
        let steady = refs.values().filter(|r| r.tier() == Tier::Steady).count();
        assert!(steady > 100, "too few steady-grid references: {steady}");
        assert!(steady < refs.len(), "expected drifting references too");
    }

    #[test]
    fn parses_every_key_spelling_rekordbox_and_stratum_emit() {
        let am = MusicalKey { pc: 9, minor: true };
        for text in ["Am", "am", " Am ", "A minor", "Amin", "8A"] {
            assert_eq!(parse_key(text), Some(am), "failed on {text:?}");
        }
        let c = MusicalKey { pc: 0, minor: false };
        for text in ["C", "C major", "Cmaj", "8B"] {
            assert_eq!(parse_key(text), Some(c), "failed on {text:?}");
        }
    }

    #[test]
    fn enharmonic_spellings_are_the_same_key() {
        // This is the reason keys are compared as pitch classes: Rekordbox
        // writes flats, stratum-dsp writes sharps, and a string comparison
        // would score every flat key as a miss.
        assert_eq!(parse_key("Abm"), parse_key("G#m"));
        assert_eq!(parse_key("Db"), parse_key("C#"));
        assert_eq!(parse_key("Bbm"), parse_key("A#m"));
        // Typographic accidentals, as some taggers write them.
        assert_eq!(parse_key("F\u{266f}m"), parse_key("F#m"));
        assert_eq!(parse_key("E\u{266d}m"), parse_key("D#m"));
        // Wrap-around at the ends of the scale.
        assert_eq!(parse_key("Cb"), Some(MusicalKey { pc: 11, minor: false }));
        assert_eq!(parse_key("B#"), Some(MusicalKey { pc: 0, minor: false }));
    }

    #[test]
    fn rejects_what_is_not_a_key() {
        for text in ["", "   ", "H", "Xm", "13A", "0A", "8C", "Am7", "minor"] {
            assert_eq!(parse_key(text), None, "accepted {text:?}");
        }
    }

    #[test]
    fn camelot_follows_the_rekordbox_convention_not_the_crates() {
        // 8A = A minor, 8B = C major, A = minor. stratum_dsp::Key::numerical()
        // uses the inverse (A = major, 1A = C), which is exactly why we derive
        // the wheel position ourselves.
        assert_eq!(parse_key("Am").unwrap().camelot(), (8, false));
        assert_eq!(parse_key("C").unwrap().camelot(), (8, true));
        assert_eq!(parse_key("Em").unwrap().camelot(), (9, false));
        assert_eq!(parse_key("G").unwrap().camelot(), (9, true));
        assert_eq!(parse_key("Dm").unwrap().camelot(), (7, false));
        assert_eq!(parse_key("F").unwrap().camelot(), (7, true));
        assert_eq!(parse_key("E").unwrap().camelot(), (12, true));
        assert_eq!(parse_key("Abm").unwrap().camelot(), (1, false));
    }

    #[test]
    fn camelot_round_trips_through_parsing() {
        for pc in 0..12u8 {
            for minor in [false, true] {
                let key = MusicalKey { pc, minor };
                let (n, is_major) = key.camelot();
                let text = format!("{n}{}", if is_major { "B" } else { "A" });
                assert_eq!(parse_key(&text), Some(key), "{text} != {key:?}");
            }
        }
    }

    #[test]
    fn stratum_keys_convert_by_pitch_class() {
        assert_eq!(
            from_stratum(stratum_dsp::Key::Minor(9)),
            MusicalKey { pc: 9, minor: true }
        );
        assert_eq!(
            from_stratum(stratum_dsp::Key::Major(0)),
            MusicalKey { pc: 0, minor: false }
        );
        // Their pitch class is a u32 documented as 0..11; fold anything else
        // rather than panic on an index.
        assert_eq!(
            from_stratum(stratum_dsp::Key::Major(12)),
            MusicalKey { pc: 0, minor: false }
        );
    }

    #[test]
    fn classify_key_separates_mixable_misses_from_wrong_ones() {
        let am = parse_key("Am").unwrap();
        assert_eq!(classify_key(Some(am), am), KeyVerdict::Exact);
        // Relative major: same Camelot number, other letter.
        assert_eq!(classify_key(parse_key("C"), am), KeyVerdict::Relative);
        // One step around the wheel, same mode — a fifth away either way.
        assert_eq!(classify_key(parse_key("Em"), am), KeyVerdict::Fifth);
        assert_eq!(classify_key(parse_key("Dm"), am), KeyVerdict::Fifth);
        // A semitone off is not mixable and must not be excused.
        assert_eq!(classify_key(parse_key("Bbm"), am), KeyVerdict::Wrong);
        assert_eq!(classify_key(None, am), KeyVerdict::NoResult);
    }

    #[test]
    fn classify_key_calls_out_a_wrong_mode_on_the_right_root() {
        // 12 % of the first real run landed here: right tonic, wrong mode. It is
        // not mixable and not "close", but it is a different failure from a
        // random miss, and reporting it as plain "wrong" hid that.
        let am = parse_key("Am").unwrap();
        assert_eq!(classify_key(parse_key("A"), am), KeyVerdict::Parallel);
        let c = parse_key("C").unwrap();
        assert_eq!(classify_key(parse_key("Cm"), c), KeyVerdict::Parallel);
        // Parallel must win over the wheel-distance rules, not fall through
        // to Fifth or Wrong.
        let (n_am, _) = am.camelot();
        let (n_a, _) = parse_key("A").unwrap().camelot();
        assert_ne!(n_am, n_a, "parallel keys sit far apart on the wheel");
    }

    #[test]
    fn classify_key_wraps_around_the_wheel() {
        // 1A and 12A are neighbours, so the step must be computed modulo 12.
        let one = parse_key("Abm").unwrap();
        assert_eq!(one.camelot(), (1, false));
        assert_eq!(classify_key(parse_key("Dbm"), one), KeyVerdict::Fifth);
        assert_eq!(classify_key(parse_key("Ebm"), one), KeyVerdict::Fifth);
    }

    #[test]
    fn key_tally_counts_and_survives_being_empty() {
        let mut t = KeyTally::default();
        assert_eq!(t.total(), 0);
        assert_eq!(t.pct(0), 0.0);
        t.add(KeyVerdict::Exact);
        t.add(KeyVerdict::Relative);
        t.add(KeyVerdict::Parallel);
        t.add(KeyVerdict::Wrong);
        assert_eq!(t.total(), 4);
        assert_eq!(t.pct(t.exact), 25.0);
        assert_eq!(t.pct(t.parallel), 25.0);
        assert_eq!(t.pct(t.wrong), 25.0);
    }

    #[test]
    fn the_reference_set_carries_keys() {
        let refs = parse_reference(REFERENCE_CSV);
        let keyed = refs.values().filter(|r| r.key.is_some()).count();
        assert!(keyed > 500, "expected a key reference, got {keyed} rows");
    }

    #[test]
    fn spelled_shows_note_and_camelot() {
        assert_eq!(parse_key("Am").unwrap().spelled(), "Am (8A)");
        assert_eq!(parse_key("Db").unwrap().spelled(), "C# (3B)");
    }

    #[test]
    fn the_bundled_ffmpeg_is_where_the_benchmark_expects_it() {
        // A missing sidecar would otherwise show up as "every track failed".
        assert!(ffmpeg().is_file(), "no sidecar at {}", ffmpeg().display());
    }
}
